### ISSUE TITLE
Display stats in monospace font

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#115]
Player and Game Stats are currently shown using the default font. This results in different sizes for different numbers, which makes the text jump around while moving / whenever a number changes significantly. This can be avoided by displaying the stats in monospace font.
One main complication is that currently all menu text is collected into a single string and that string passed to a single `draw_text` call which only allows a single font. Displaying everything in monospace is the easiest solution, but might look bad. The best solution would be to draw different parts in different fonts, and manually set the respectively correct X and Y coordinates based on `AMyHUD::getTextSize`.

**Comment by LukeSaward1** [comment]
![image](https://github.com/user-attachments/assets/215360b9-8a9d-4fb6-bfcf-fc57b469f5c9)
