### ISSUE TITLE
Control Camera instead of Player

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#125]
For #114 one cool feature would be to be able to control the camera instead of the character with movement keys. Workarounds would be to ~~use / set ClientCheatGhost~~ [impossible due to `#if !UE_BUILD_SHIPPING` around the code], or to manually calculate / update a player's position (setting velocity to 0 in every single frame) to move them around.

**Comment by LukeSaward1** [comment]
CharacterCameraComponent has a SceneComponent which has AbsoluteLocation, AbsoluteRotation, RelativeLocation and RelativeRotation within it. I have already accessed that within my cheat table and I am able to modify the player's position.

One way we could do it is disable player movement, or do it the Universal Unreal Unlocker (UUU) way, which I'm still researching.

**Comment by LukeSaward1** [comment]
We have successfully got console commands working in Refunct through gdb commands.
The command `ToggleDebugCamera` is the command we want for this.
