### ISSUE TITLE
Change Platform Rise Speed

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#130]
(Functionality from Ero's Tool)

**Comment by LukeSaward1** [comment]
With pointer paths, this is not very difficult to do.

**Comment by LukeSaward1** [comment]
We only need 1 offset now we have every object in the game. We can simply get the class of the LevelRoot and get the Speed field using its offset.

**Comment by LukeSaward1** [comment]
As of the latest map editor version, it is possible to do this.

Closing.
