### ISSUE TITLE
Reduce Practice State Wait Time

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#131]
Related to #4.

With #130 the practice states can set the rise speed of platforms to a very high number, requiring only 0.5 seconds for them to be fully risen, reducing the wait time from 18 frames to 2. This also further reduces the problems of overlapping music.

**Comment by LukeSaward1** [comment]
With the current implementation, we already have access to every cluster and thus I believe there is no need to rely on #130 anymore.

Closing.
