### ISSUE TITLE
Step-Frame mode completely freezes the game

### ISSUE THREAD

**Issue by LukeSaward1** [oberien/refunct-tas#137]
Step-Frame mode completely freezes the game and I can't input anything until I quit out of refunct-tas.

**oberien — Today at 23:16
Remind me to take a look at it tomorrow.**

Here you go.

**Comment by oberien** [comment]
Please provide reproduction instructions.

**Comment by LukeSaward1** [comment]
Press M while in frame-step mode and try to frame advance.
