### ISSUE TITLE
Rewind frames in a recording

### ISSUE THREAD

**Issue by LukeSaward1** [oberien/refunct-tas#148]
Dat Boi in Discord asked this:
> would it be possible to add a bind that goes backwards a frame, the opposite of frame advance 
so i dont have to meticulously play back the tas frame by frame seeing what i did wrong

Yep, but to an extent.
After a few more messages, they suggested this:
> i think there should be 2 binds for rewinding, one has an input box where you can specify how many frames to go back, itll then go to a new game and speed up to the frame indicated, and the other simply rewinds player positions by a frame
mode1 would be for buttons and mode 2 for general movement

Quite possible. I can integrate that with #138.

**Comment by oberien** [comment]
Merged into #138
