### ISSUE TITLE
Add In-Game Minimap

### ISSUE THREAD

**Issue by LukeSaward1** [oberien/refunct-tas#150]
> Raxel: "It would be cool if there was a minimap"

Probably a Camera actor overlooking the entire map.

**Comment by oberien** [comment]
Or Ero's minimap with a dot where your position is.

**Comment by LukeSaward1** [comment]
> Or Ero's minimap with a dot where your position is.

Once we figure out how to draw images to the HUD, that's an option, hence why I added the `needs-research` label.

**Comment by oberien** [comment]
Implemented in 9bcc7f0.
