### ISSUE TITLE
MapEditor: Adjust height of cluster before it is risen

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#235]
![image](https://github.com/oberien/refunct-tas/assets/95598570/05703225-db34-460e-80dd-6a7c8a86fd2b)
Image shows unrisen platform sticking above water, being able to move the clusters starting position down ~250 units (without effecting the risen platforms positions) would solve the issue.

In the base game the starting position of the cluster is entirely based on the highest platform, so along with the ability to freely adjust the starting position, it would also be convenient (but not necessary) to have a button that automatically adjusts the starting position based on the highest platform's height/position.

**Comment by LukeSaward1** [comment]
> the starting position of the cluster is entirely based on the highest platform
Unless I'm misunderstanding something, there is a field called `SourcePosition` which determines where the starting position of the cluster is. Modifying this field's X, Y and Z values will allow you to change where the cluster starts.

**Comment by oberien** [comment]
Will clusters always rise to z=0 no matter their initial `SourcePosition` or do we need to change the rising-height?

**Comment by LukeSaward1** [comment]
> Will clusters always rise to z=0 no matter their initial `SourcePosition` or do we need to change the rising-height?

It goes to 0 no matter what.
