### ISSUE TITLE
MapEditor: Ability to work with absolute dimensions of platforms

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#237]
Currently working with the Scale values of platforms is annoying as you need to know the figure out the initial size of the platform if you want to be precise. If the Map Editor's element menu were to only display the dimensions of the currently selected platform, it would make map editing a lot easier. However, the ability to directly edit those dimensions would be even better.

**Comment by MiningPie** [comment]
If the platform values have to be stored as scales, a possible solution could allow the player to type an exact desired dimension into the scale part with some prefix (example input shown in image), and then the base dimensions and desired dimension could be used to calculate the scale to then store to the map file.
![image](https://github.com/oberien/refunct-tas/assets/95598570/81894406-b8ea-4cdf-9950-5da5e1eab9cf)

**Comment by LukeSaward1** [comment]
With the function `UKismetSystemLibrary::GetActorBounds(AActor)` which returns two FVectors (`Origin`, which is the center of the object, and `BoxExtend` which are the world dimensions of the object.)

These values are affected by scale.

**Comment by MiningPie** [comment]
If this does completely get rid of the scale values in the menu, it may be worth adding a "reset dimensions" button to return the dimensions to the platform's default values. Otherwise, it would be annoying to have to reset all values and reposition the platform, as finding what the original values were by guessing whether the platform looks unstretched or not would be annoying.

Displaying base values of the dimensions in the element menu is an easier (but slightly less convenient) way to solve the same issue.

**Comment by oberien** [comment]
It is already possible via the "Reset to default values" button, which resets location, rotation and scale back to their original values.
