### ISSUE TITLE
MapEditor: (invalid value) text despite displaying a valid value

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#238]
Extremely minor and should definitely be low priority bug, but it has been somewhat annoying me.

https://github.com/oberien/refunct-tas/assets/95598570/71b82297-5e2b-44f4-ae1f-d4e5e4fe6788

If you input an invalid value in a field and then exit and reopen the menu, it will continue to display the value is invalid (despite containing a valid value) until moving the cursor to that field again.

If this requires more than an easy fix it is, im fine with this issue being closed as it is completely something I am able to live with.

**Comment by MiningPie** [comment]
Could be fixed by only allowing numbers in these sorts of fields (would also solve the issue of moving around and then accidentally inputting a bunch of spaces in the fields)

**Comment by LukeSaward1** [comment]
The label seemingly isn't reset.
Easy fix.
