### ISSUE TITLE
Map Editor: Typo in Element Selection Menu text

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#269]
![image](https://github.com/oberien/refunct-tas/assets/95598570/91eee796-243b-425a-9d02-e8a3cb7d2fe5)
There is a p instead of c after the b

![image](https://github.com/oberien/refunct-tas/assets/95598570/8e738536-2cda-4ff4-9a8d-4bc917b83e0a)
Error text shows it correctly, however it is in a different order

**Comment by LukeSaward1** [comment]
Shit.
Will fix that later today.
