### ISSUE TITLE
Map Editor: Practice Mode breaks map editor

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#273]
![image](https://github.com/oberien/refunct-tas/assets/95598570/48679f57-8bbb-417e-aa22-55fcd5e98772)

Map gets fixed after closing and reopening map. No clue if there is a pattern in how the platforms are messed up.

**Comment by MiningPie** [comment]
https://github.com/oberien/refunct-tas/assets/95598570/16612572-894c-4522-b6d5-2be1449e7741

clear showcase of the issue

**Comment by LukeSaward1** [comment]
Additionally, another variant of this, where you don't even need the map editor.

Reproduction steps:

- Load refunct-tas (I used [this build](https://ci.appveyor.com/api/buildjobs/jwl3t9djglbl3vwq/artifacts/build%2Fpractice-windows.zip))
- Practice Button 30 or 31
- Hit New Game
- Look at cluster 24 and 25's springpads

**Comment by MiningPie** [comment]
It seems the pattern of the chaos caused by this issue is due to the scaling being applied in reverse. (So this is definitely distinct from #281)
![image](https://github.com/oberien/refunct-tas/assets/95598570/b23025c0-e1a3-4b3a-817b-1517fe635772)
This platform that has a SizeX of .1 now is extremely large after performing the same steps as in the replication video above. I also noticed that platforms that are completely unscaled seem unaffected by this issue.

**Comment by LukeSaward1** [comment]
I think I know a fix for this, gonna be working on it soon.

**Comment by LukeSaward1** [comment]
Shouldn't've been closed, my mistake

**Comment by oberien** [comment]
This wasn't fixed by the PR?

**Comment by LukeSaward1** [comment]
Oh wait, it mightve been, lemme test rq

**Comment by LukeSaward1** [comment]
Yeah, it was. That's what happens when I don't double-check absolutely everything.
Closing, for real this time.
