### ISSUE TITLE
Practice states don't remove underwater audio effect

### ISSUE THREAD

**Issue by MiningPie** [oberien/refunct-tas#287]
https://github.com/oberien/refunct-tas/assets/95598570/9d5d0d80-6034-4194-90d5-ac1095d5f300

Resetting a practice state does not clear the underwater audio effect. In the video above you can hear how the sounds are still muffled until I re-exit the water to clear the effect.

**Comment by LukeSaward1** [comment]
I have a few ideas of how to fix this, lemme test.

**Comment by LukeSaward1** [comment]
I can just disable the underwater EQ entirely to make it consistent across every platform.

**Comment by LukeSaward1** [comment]
Well this is the easiest fix of my fucking life.
```rust
if class_name == "SoundMix" {
    object.get_field("bApplyEQ").unwrap::<BoolValueWrapper>().set(false);
}
```
So fucking easy.
