### ISSUE TITLE
Display Timer on Screen

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#65]
Add a setting to display the Refunct-timer and another option to display an actual IGT (sum up delta-times; not the best due to repeated floating point addition, but for ~10min runs this should be fine(tm)). For the Refunct-timer we should use the function that Refunct itself uses for time-recording.

**Comment by oberien** [comment]
The blueprint function `Get Accurate Real Time` [calls `FPlatformTime::Seconds`](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Runtime/Engine/Private/GameplayStatics.cpp#L2202-L2207). `FPlatformType` [is typedef'ed](https://docs.unrealengine.com/en-US/API/Runtime/Core/Unix/FPlatformTime/index.html) to use a clock from the OS. For example on Linux it calls [`FUnixTime::Seconds`](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Runtime/Core/Public/Unix/UnixPlatformTime.h#L19-L24), which internally calls `clock_gettime(ClockSource, &ts);`, where `ClockSource` [is initialized](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Runtime/Core/Private/Unix/UnixPlatformTime.cpp#L29-L38) when the game starts [by benchmarking and checking](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Runtime/Core/Private/Unix/UnixPlatformTime.cpp#L161-L226) different clock types and selecting the best available one.

In the end we should just call `FPlatformTime::Seconds` directly. That function has one input-argument, which is any `UObject` from that world (from which the world is gotten by calling `GetWorldChecked`). Passing something like the `AMyPlayerCharacter` should work.  
It has two out-arguments: `int32& Seconds, float& PartialSeconds`.

**Comment by LukeSaward1** [comment]
This is the closest thing I can find to `FPlatformTime::Seconds` from scouring the UE docs for a few mins: https://docs.unrealengine.com/5.1/en-US/API/Runtime/Core/Unix/FUnixTime/Seconds/
Not sure if this is the correct one. FPlatformTime doesn't seem to have a `Seconds` field.

**Comment by oberien** [comment]
It seems that we don't have the `FPlatformTime::Seconds` function available. This means we'll need to go deeper and call a lower-level function / reconstruct / reimplement `FPlatformTime::Seconds` ourselves.

**Comment by LukeSaward1** [comment]
Yippee! /s

that's gonna take some work.
If reimplementation is required, it's definitely something you would have to do/help me with, since I know next to nothing about doing that.

**Comment by LukeSaward1** [comment]
Calling 
```cpp
UGameplayStatics::GetAccurateRealTime(UObject WorldReferenceObject)
``` is exactly what we need. Once IGT-splits is merged to master, this issue can be closed.
