### ISSUE TITLE
Move back to Main Menu when ESC is pressed

### ISSUE THREAD

**Issue by oberien** [oberien/refunct-tas#95]
When a user presses ESC and the in-game menu opens, the refunct-tas UI isn't rendered. However, any keys pressed still register in the refunct-tas menu (including arrows and enter). Therefore, it might be best to close any open refunct-tas menu when ESC is pressed and go back to the main menu.

One problem might be TAS mode (or any mode which listens to `on_key*` events) still trigger even when in the main menu.

**Comment by LukeSaward1** [comment]
Probably best to check whether the menu is open unless we want to deal with UE4 keybinds.

**Comment by LukeSaward1** [comment]
To do this we can hook `UUserWidget::AddToScreen`
